POST http://localhost:3001/produtos HTTP/1.1
content-type: application/json

{
    "nome": "caneta",
    "preco": 1,
    "cor": "azul"
}

###

GET http://localhost:3001/produtos HTTP/1.1

### 

GET http://localhost:3001/produtos/ff313947-e7b9-4908-a514-a578a133b813 HTTP/1.1

###

PUT http://localhost:3001/produtos/b6b6a9ab-da46-4c20-8421-dcab98b771bc HTTP/1.1
content-type: application/json

{
    "preco": 15.95
}

###

DELETE http://localhost:3001/produtos/644632a4-128f-4b06-806f-0be3533d84d0 HTTP/1.1