POST http://localhost:3001/produtos HTTP/1.1
content-type: application/json

{
    "nome": "caderno",
    "preco": 5,
    "cor": "verde"
}

###

GET http://localhost:3001/produtos HTTP/1.1

### 

GET http://localhost:3001/produtos/ff313947-e7b9-4908-a514-a578a133b813 HTTP/1.1

###

PUT http://localhost:3001/produtos/eae444d2-61c3-4ab3-b6b5-2b5304c85497 HTTP/1.1
content-type: application/json

{
    "cor": "amarelo"
}

###

DELETE http://localhost:3001/produtos/blablabla HTTP/1.1